# Generated by Django 5.1.1 on 2025-06-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClashTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('stage', models.CharField(choices=[('group', 'Group Stage'), ('quarter', 'Quarter Finals'), ('semi', 'Semi Finals'), ('final', 'Championship Final')], default='group', max_length=20)),
            ],
        ),
    ]
