# Generated by Django 5.1.6 on 2025-03-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='freefire',
            new_name='freefire',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='playstation',
            new_name='playstation',
        )
    ]
