# Generated by Django 5.1.6 on 2025-06-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_clashtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='clashtournament',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
