# Generated by Django 5.1.6 on 2025-02-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_paystackrecipient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystackrecipient',
            name='payment_type',
        ),
    ]
