# Generated by Django 5.1.6 on 2025-06-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_clashtournament_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clashtournament',
            name='date',
            field=models.DateField(),
        ),
    ]
