# Generated by Django 5.1.6 on 2025-02-26 21:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='last_checked',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
