# Generated by Django 5.1.6 on 2025-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_investment_last_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment')], max_length=10),
        ),
    ]
