# Generated by Django 5.1.6 on 2025-06-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_clashtournament_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clashtournament',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
