# Generated by Django 5.1.6 on 2025-02-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paystackrecipient',
            name='recipient_code',
            field=models.CharField(max_length=100),
        ),
    ]
