# Generated by Django 5.1.6 on 2025-02-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_paystackrecipient_recipient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubg', models.IntegerField()),
                ('codm', models.IntegerField()),
                ('fortnite', models.IntegerField()),
                ('free_fire', models.IntegerField()),
                ('apple', models.IntegerField()),
                ('google', models.IntegerField()),
                ('steam', models.IntegerField()),
                ('play_station', models.IntegerField()),
            ],
        ),
    ]
