# Generated by Django 5.1.6 on 2025-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_squadplayer_squadtournament_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('esim', 'ESIM'), ('ecommerce', 'E-Commerce'), ('games', 'Games'), ('gift-cards', 'Gift Cards')], max_length=20)),
            ],
        ),
    ]
