# Generated by Django 5.1.6 on 2025-03-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paystackrecipient',
            name='recipient_code',
        ),
    ]
