# Generated by Django 5.1.6 on 2025-03-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='device_type',
            field=models.CharField(choices=[('Mobile', 'Mobile'), ('Latop/Desktop', 'Laptop/Desktop')], default='Laptop/Desktop', max_length=20),
        ),
    ]
