# Generated by Django 5.1.6 on 2025-03-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_loginhistory_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillBoardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='billboard_images/')),
            ],
        ),
    ]
