# Generated by Django 5.1.6 on 2025-06-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_crypto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('card_code', models.CharField(max_length=50)),
                ('card_image', models.FileField(upload_to='trade/cards/')),
                ('card_type', models.CharField(max_length=10)),
            ],
        ),
    ]
