# Generated by Django 5.1.6 on 2025-06-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
