# Generated by Django 5.1.6 on 2025-03-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_billboardimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_earnings',
        ),
    ]
