# Generated by Django 5.1.6 on 2025-06-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_trade_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='card_image',
            field=models.FileField(blank=True, null=True, upload_to='trade/cards/'),
        ),
    ]
