# Generated by Django 5.1.6 on 2025-03-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_remove_userprofile_total_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
