# Generated by Django 5.1.6 on 2025-03-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_referral_referral_code_alter_referral_referrer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3, unique=True)),
                ('rate_to_ghs', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
