# Generated by Django 5.1.6 on 2025-03-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('refund', 'Refund')], max_length=10),
        ),
    ]
