# Generated by Django 5.1.6 on 2025-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crypto/'),
        ),
    ]
