# Generated by Django 5.1.6 on 2025-06-29 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20250308_1629'),
        ('shop', '0023_crypto_image'),
    ]

    operations = [
    ]
