# Generated by Django 5.1.6 on 2025-03-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_billboardimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboardimage',
            name='image_url',
            field=models.URLField(),
        ),
    ]
