# Generated by Django 5.1.6 on 2025-07-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_crypto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billboardimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='billboardimage',
            name='image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billboardimage',
            name='image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billboardimage',
            name='image3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
