# Generated by Django 5.1.6 on 2025-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='received_reward',
            field=models.BooleanField(default=False),
        ),
    ]
