# Generated by Django 5.1.6 on 2025-10-13 17:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_datapurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reference',
            field=models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=100, null=True),
        ),
    ]
