# Generated by Django 5.1.6 on 2025-10-13 17:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_withdrawalrequest_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
